name: "Semantic PR and Commit Messages"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Validate the pull request
        uses: namchee/conventional-pr@v0.15.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          issue: false # Do not require an issue for now
